### ISSUE TITLE
Is it possible to support Android 4.4 on M3 and M64

### ISSUE THREAD

**Issue by andrewleo** [BPI-SINOVOIP/BPI-M3-bsp#18]
I need Android 4.4 image which can run on M3 and M64, wonder if anyone has the image, or it is possible to run Android 4.4 on M3 and M64?

**Comment by BPI-SINOVOIP** [comment]
Sorry, M3 support android 5.1 and m64 support android 6.1 and android 7.0,  both are not support android 4.4.
