### ISSUE TITLE
README.md wrong (as usual)

### ISSUE THREAD

**Issue by ThomasKaiser** [BPI-SINOVOIP/BPI-M3-bsp#2]
Unbelievable. Your 'instructions' seem to be copy&paste from the M2's BSP. It should read

sudo dd if=$P/boot0_sdcard.fex  of=$O bs=1k seek=8
sudo dd if=$P/u-boot.fex        of=$O bs=1k seek=19096
sudo dd if=$P/sunxi_mbr.fex     of=$O bs=1k seek=20480
sudo dd if=$P/boot-resource.fex of=$O bs=1k seek=36864
sudo dd if=$P/env.fex           of=$O bs=1k seek=69632
sudo dd if=$P/boot.fex          of=$O bs=1k seek=86016

instead! There is no "bootloader.fex" in this 'SDK'

**Comment by BPI-SINOVOIP** [comment]
Modify it .
