### ISSUE TITLE
中文？安装选1报错

### ISSUE THREAD

**Issue by jacky-yan** [BPI-SINOVOIP/BPI-M3-bsp#4]
/root/git/BPI-M3-bsp/allwinner-tools/toolchain/bin/arm-linux-gnueabi-gcc -DDO_DEPS_ONLY \
        -g  -Os   -fno-common -ffixed-r8 -msoft-float   -D__KERNEL__ -I/root/git/BPI-M3-bsp/u-boot-sunxi/include -I/root/git/BPI-M3-bsp/u-boot-sunxi/include/openssl -fno-builtin -ffreestanding -nostdinc -isystem  -pipe  -DCONFIG_ARM -D__ARM__ -mfpu=neon -D__NEON_SIMD__         -mcpu=cortex-a7 -Werror -Wall -Wstrict-prototypes      \
        -o lib/asm-offsets.s lib/asm-offsets.c -c -S
/bin/bash: /root/git/BPI-M3-bsp/allwinner-tools/toolchain/bin/arm-linux-gnueabi-gcc: cannot execute binary file
Makefile:649: recipe for target 'lib/asm-offsets.s' failed
make[1]: **\* [lib/asm-offsets.s] Error 126
make[1]: Leaving directory '/root/git/BPI-M3-bsp/u-boot-sunxi'
Makefile:36: recipe for target 'u-boot' failed
make: **\* [u-boot] Error 2

 Build success!

**Comment by jacky-yan** [comment]
/bin/bash: /root/git/BPI-M3-bsp/allwinner-tools/toolchain/bin/arm-linux-gnueabi-gcc: cannot execute binary file
dirname: missing operand
还有很多dirname: missing operand

**Comment by BPI-SINOVOIP** [comment]
HI:
     you can try it .

Install Compiler tools
Step 1:
   sudo apt-get install build-essential libncurses5-dev u-boot-tools qemu-user-static\ debootstrap git binfmt-support libusb-1.0-0-dev pkg-config

Step 2:
   sudo apt-get install gcc-arm-linux-gnueabihf

**Comment by ThomasKaiser** [comment]
Why do you recommend installing 'gcc-arm-linux-gnueabihf' if the BSP you deliver contains already allwinner-tools/toolchain/bin/arm-linux-gnueabi-gcc? Did you read the error message above? Or do you simply try to close any issue here without spending any time on it?

Especially why do you recommend installing a more recent version of gcc-arm-linux-gnueabihf if you already know that it can't work: https://github.com/BPI-SINOVOIP/BPI-M3-bsp/issues/1 The provided build.sh **only** works with the included toolchain so why do you recommend installing another one?

Last and most important thing: The Readme here doesn't contain the most important information (but that's SinoVoip style as usual). The build environment is intended to run on a x86 system. The error message above ("cannot execute binary file") indicates that @jacky-yan tries to compile on a different architecture.
