### ISSUE TITLE
make[2]: *** No rule to make target 'output/lib/firmware/./', needed by 'output/lib/firmware/ti_3410.fw'.  Stop.

### ISSUE THREAD

**Issue by jim60105** [BPI-SINOVOIP/BPI-M3-bsp#7]
I'm trying to compile this on ArchLinux:

```
[jim@jim-hd710-archlinux ~]$ uname -a
    Linux jim-hd710-archlinux 4.1.2-2-ARCH #1 SMP PREEMPT Wed Jul 15 08:30:32 UTC 2015 x86_64 GNU/Linux
```

I "git clone https://github.com/BPI-SINOVOIP/BPI-M3-bsp.git" at folder "/home/jim/bananapi/"

I run "./build.sh", choosing "3. BPI_M3_LCD7" and "1. Build all, uboot and kernel and pack to download images.", then I get:

```
make[2]: *** No rule to make target 'output/lib/firmware/./', needed by 'output/lib/firmware/ti_3410.fw'.  Stop.
    make[2]: *** Waiting for unfinished jobs....
      MKDIR   output/lib/firmware/kaweth/
      MKDIR   output/lib/firmware/emi26/
      MKDIR   output/lib/firmware/emi62/
    Makefile:1140: recipe for target '_modinst_post' failed
    make[1]: *** [_modinst_post] Error 2
    make[1]: Leaving directory '/home/jim/bananapi/BPI-M3-bsp/linux-sunxi'
    Makefile:57: recipe for target 'kernel' failed
    make: *** [kernel] Error 2

     Build success!

```

I delete all files except ".git", and do "git reset --hard".
Then I create the folder "/home/jim/bananapi/BPI-M3-bsp/linux-sunxi/output/lib/firmware" manually to avoid the error.

And run "./build.sh" with same numbers input with successful.

Just post this to tell you the problem. Sorry for my poor English.

**Comment by cudnn** [comment]
你现在编译成功了吗 我想在m3上直接编译   跟你一样的错误

**Comment by jim60105** [comment]
那error是抓不到資料夾
先手動建立就能解決
我上面有寫

**Comment by BPI-SINOVOIP** [comment]
Try to using the docker image to avoid compile environment issues. https://hub.docker.com/r/sinovoip/bpi-build/
